---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  labels:
    app: resume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - name: resume
          image: ghcr.io/abatilo/resume:DOCKER_TAG
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resume
spec:
  selector:
    app: resume
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: resume
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: resume
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "Middleware"
metadata:
  name: resume
spec:
  headers:
    forceSTSHeader: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    referrerPolicy: "no-referrer-when-downgrade"
    contentTypeNosniff: true
    contentSecurityPolicy: "upgrade-insecure-requests"
    browserXssFilter: true
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      "Permissions-Policy": "geolocation=(); midi=(); notifications=(); push=(); sync-xhr=(); microphone=(); camera=(); magnetometer=(); gyroscope=(); speaker=(self); vibrate=(); fullscreen=(self); payment=();"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: resume-http-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "IngressRoute"
metadata:
  name: resume
spec:
  entryPoints: ["web"]
  routes:
    - match: "Host(`aaronbatilo.dev`, `www.aaronbatilo.dev`) && Path(`/resume`, `/resume.pdf`)"
      kind: "Rule"
      middlewares:
        - name: resume-http-to-https
        - name: resume
      services:
        - name: resume
          port: 80
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "IngressRoute"
metadata:
  name: resume-secure
spec:
  entryPoints: ["websecure"]
  routes:
    - match: "Host(`aaronbatilo.dev`, `www.aaronbatilo.dev`) && Path(`/resume`, `/resume.pdf`)"
      kind: "Rule"
      middlewares:
        - name: resume
      services:
        - name: resume
          port: 80
