---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  labels:
    app: resume
spec:
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: resume
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: resume
      containers:
        - name: resume
          image: ghcr.io/abatilo/resume:DOCKER_TAG
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              memory: 128Mi
---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: resume
spec:
  host: aaronbatilo.dev
  scaledownPeriod: 120
  scaleTargetRef:
    deployment: resume
    service: resume
    port: 80
  replicas:
    min: 0
    max: 5
---
apiVersion: v1
kind: Service
metadata:
  name: resume
spec:
  selector:
    app: resume
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: resume
spec:
  dnsNames:
    - aaronbatilo.dev
    - www.aaronbatilo.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: resume-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: resume
spec:
  headers:
    customRequestHeaders:
      # Force host header because keda-http-addon only supports one host at a
      # time
      host: aaronbatilo.dev
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "IngressRoute"
metadata:
  name: resume
spec:
  entryPoints: ["websecure"]
  tls:
    secretName: resume-cert
  routes:
    - match: "Host(`aaronbatilo.dev`, `www.aaronbatilo.dev`) && Path(`/resume`, `/resume.pdf`)"
      kind: "Rule"
      middlewares:
        - name: security-headers
          namespace: traefik
      services:
        # - name: resume
        #   port: 80
        - name: keda-add-ons-http-interceptor-proxy
          namespace: keda
          port: 8080
