name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: abatilo/workflows/.github/workflows/ci.yml@main
    permissions:
      id-token: write
      packages: write
      contents: read
    with:
      name: blog
