name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy
    permissions:
      packages: write
      contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1

      - name: Set EKS context
        run: |
          aws eks update-kubeconfig --name usw2-r

      - name: Create buildx daemon on EKS cluster
        uses: docker/setup-buildx-action@v1
        with:
          driver: kubernetes
          driver-opts: |
            replicas=1
            namespace=buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/abatilo/resume:${{ github.sha }}
          context: .
          file: ./Dockerfile
          cache-from: type=registry,ref=ghcr.io/abatilo/resume:buildcache
          cache-to: type=registry,ref=ghcr.io/abatilo/resume:buildcache,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/abatilo/resume

      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: ghcr.io/abatilo/resume:${{ github.sha }}
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/abatilo/resume

      - name: Deploy
        run: |
          sed -i 's/DOCKER_TAG/${{ github.sha }}/' resume.yaml
          kubectl apply -f resume.yaml
