name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  deploy:
    uses: abatilo/workflows/.github/workflows/ci.yml@main
    permissions:
      id-token: write
      packages: write
      contents: read
    with:
      name: resume

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - run: |
          echo "Built from ${{ github.repository }}" > resume.pdf
          GOOS=darwin GOARCH=arm64 go build -o resume-darwin-arm64 main.go
          GOOS=linux GOARCH=amd64 go build -o resume-linux-amd64 main.go
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: |
            resume-darwin-arm64
            resume-linux-amd64
