name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy
    permissions:
      id-token: write
      packages: write
      contents: read
    env:
      AWS_ROLE_ARN: arn:aws:iam::717012417639:role/srv_ops
      AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1

      - name: assume role
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

      - name: Set EKS context
        run: |
          aws eks update-kubeconfig --name usw2-r

      - name: Create buildx daemon on EKS cluster
        uses: docker/setup-buildx-action@v1
        with:
          driver: kubernetes
          driver-opts: |
            replicas=1
            namespace=buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/abatilo/resume:${{ github.sha }}
          context: .
          file: ./Dockerfile
          cache-from: type=registry,ref=ghcr.io/abatilo/resume:buildcache
          cache-to: type=registry,ref=ghcr.io/abatilo/resume:buildcache,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/abatilo/resume

      - name: Deploy
        run: |
          sed -i 's/DOCKER_TAG/${{ github.sha }}/' resume.yaml
          kubectl apply -f resume.yaml
