name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/abatilo/resume:${{ github.sha }}
          context: .
          file: ./Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/abatilo/resume

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          aws eks update-kubeconfig --name usw2-r
          sed -i 's/DOCKER_TAG/${{ github.sha }}/' resume.yaml
          kubectl apply -f resume.yaml
