name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  deploy:
    uses: abatilo/workflows/.github/workflows/ci.yml@main
    permissions:
      id-token: write
      packages: write
      contents: read
    with:
      name: resume
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old containers
        uses: snok/container-retention-policy@v1
        with:
          image-names: resume
          cut-off: A week ago UTC
          account-type: personal
          token: ${{ secrets.GH_PAT }}
          keep-at-least: 10
